ARG ${REPOSITORY}

# Image de base
FROM ${REPOSITORY}/python:cert

WORKDIR /app
COPY ./app /app

RUN pip install --upgrade pip
RUN pip install gunicorn

RUN python manage.py makemigration
RUN python manage.py migrate
RUN python collectstatic


FROM ${REPOSITORY}/nginx:cert
# Configurer et lancer le projet python sur le serveur nginx