version: ${VERSION}
{{$projectName := .Project}}

services:
{{range .Services}}

  {{if eq .Name "bdd" }}
    {{range .Values}}
  {{$projectName}}_{{.}}_db:
    container_name: {{$projectName}}_{{.}}_db
    image: ${REPOSITORY}/${{{.}}_IMAGE}
    # call bdd template for env
    {{end}}
  {{else}}
  {{$projectName}}_{{.Name}}:
    build:
      context: .
      args:
        REPOSITORY: $REPOSITORY
    ports:
      - ${{.Name}}_port:${{.Name}}_port
    {{if .Link}}
    depends_on:
      {{range .Link}}
      - {{.}}
      {{end}}
    {{end}}
  {{end}}
    networks:
      - {{$projectName}}-network
{{end}}

networks:
   {{$projectName}}-network:

