version: "3.4"
{{$projectName := .ProjectName -}}

services:
{{range .Services -}}

  {{- if eq .Name "BDD" -}}
    {{range .Values}}
  {{$projectName}}_{{.}}_db:
    container_name: {{$projectName}}_{{.}}_db
    image: ${REPOSITORY_PROD}/${ {{- .}}_IMAGE}
    {{retrieveComposeEnvVariable .}}
    networks:
      - net
    volumes:
      - /data/{{$projectName}}_{{.}}:/var/lib/{{.}}/data/{{$projectName}}_{{.}}
    deploy:
      placement:
        constraints:
          - node.hostname == ${ {{- .}}_PROD}
      {{end}}
  {{else}}
  {{$projectName}}_{{.Name}}:
    image: ${REPOSITORY_PROD}/${ {{- $projectName}}_{{.Name}}_IMAGE}
    {{if .Link -}}
    depends_on:
      {{range .Link -}}
      - {{$projectName}}_{{.}}_db
      {{end -}}
    {{end}}
    networks:
      - net
      - traefik_net
    deploy:
      placement:
        constraints:
          - node.hostname == ${ {{- $projectName}}_{{.Name}}_PPROD}
      labels:
        traefik.frontend.rule: Host:${ {{- $projectName}}_{{.Name}}_URL}.${DNS}
        traefik.port: ${ {{- $projectName}}_{{.Name}}_PORT}
        traefik.enable: "true"
        traefik.docker.network: traefik_net

  {{end}}
{{end}}


networks:
   net:
   traefik_net:
    external: true