version: ${VERSION_COMPOSE}
{{$projectName := .ProjectName -}}

services:
{{range .Services -}}

  {{- if eq .Name "bdd" -}}
    {{range .Values}}
  {{$projectName}}_{{.}}_db:
    container_name: {{$projectName}}_{{.}}_db
    image: ${REPOSITORY}/${ {{- .}}_IMAGE}
    # call bdd template for env
    networks:
      - {{$projectName}}-network
    {{- end -}}
  {{else}}
  {{$projectName}}_{{.Name}}:
    build:
      context: .
      args:
        REPOSITORY: ${REPOSITORY}
    {{if .Link -}}
    depends_on:
      {{range .Link -}}
      - {{$projectName}}_{{.}}_db
      {{end -}}
    {{end}}
    networks:
      - {{$projectName}}-network
  {{end}}  
{{end}}

networks:
   {{$projectName}}-network:

