version: "3.4"
{{$projectName := .ProjectName -}}

services:
{{range .Services -}}

  {{- if eq .Name "BDD" -}}
    {{range .Values}}
  {{$projectName}}_{{.}}_db:
    container_name: {{$projectName}}_{{.}}_db
    image: ${REPOSITORY_PROD}/${ {{- .}}_IMAGE}
    {{retrieveComposeEnvVariable .}}
    networks:
      - {{$projectName}}-network
    {{- end -}}
  {{else}}
  {{$projectName}}_{{.Name}}:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      args:
        REPOSITORY: ${REPOSITORY_PROD}
        PORT: ${ {{- $projectName}}_{{.Name}}_PORT}
    {{if .Link -}}
    depends_on:
      {{range .Link -}}
      - {{$projectName}}_{{.}}_db
      {{end -}}
    {{end}}
    networks:
      - {{$projectName}}-network
  {{end}}  
{{end}}

networks:
   {{$projectName}}-network:

